Implemented Account Selection Window and added registration navigation
UTDallasEPICS/Reading-MLK pull request #50
Opened 2024-09-27 12:03 UTC by thanmaiKmandala

pages/index.vue: 
- Added a "Register Now" button with logic design behind it. Button is linked to the accountSelectionWindow.vue
- Added a hover effect to the button to make it easier for user experience

pages/accountSelectionWindow.vue: 
- New file created for this issue. Basically opens up a window that gives 4 options: You can create either a "Parent", "Student", "Faculty" class or you can click on "Close" to close the window.
- Added some navigation logic to make it flow from the accountSelectionWindow to the registration forms for each respective account type. (ex. Clicking on Parent in the window will take you to the parent registration form)

docker-compose.yml:
- Updated port mapping
- If you are running with "npm run dev" and using the docker desktop, you don't need to worry about this.

2024-09-27 15:26 UTC, Duc-T-Nguyen commented
Note: 
- the create parent and create faculty buttons should not navigate to createparent and createfaculty. Those pages are not the pages we want to navigate during registration and should be instead updated to navigate to parentform and facultyform respectively.
- also we do not need to have the create student button 
- the createparent, createfaculty, and createstudent pages are for admins accounts to exclsuively have access to (requested by Rae to personally add parents, faculty, and students)

2024-09-27 16:47 UTC, OfekShaltiel-UTD commented on docker-compose.yml
Please do not change the docker-compose file. The Docker container is supposed to be Standardized for everyone in EPICS to run on 11111:5432 (or well 11111:54xx in the future). We can fix this in lab.

2024-09-27 17:00 UTC, OfekShaltiel-UTD requested changes
Added code quality comments that should be addressed before the end of the sprint.

2024-09-27 17:23 UTC, OfekShaltiel-UTD commented on docker-compose.yml
Edit: Misread the file, so I'll talk to Taz about the new app service on the docker-compose, but as regards to your pr message, we'll keep the db port as 11111:5432 for now.

2024-10-03 04:56 UTC, Duc-T-Nguyen approved these changes
pugified template, implemented requirements, and complete other issues present in initial pull request

2024-10-03 04:56 UTC, merged